# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'cocoapods', :git => 'https://github.com/dnkoutso/CocoaPods.git', :ref => '77be91d3d9b451bb438f5c1935d9e3814e630ab7'

def cp_gem(name, repo_name)
  url = "https://github.com/CocoaPods/#{repo_name}.git"
  opts = { :git => url, :branch => 'master' }
  gem name, opts
end

cp_gem 'claide',                'CLAide'
cp_gem 'cocoapods-core',        'Core'
cp_gem 'cocoapods-deintegrate', 'cocoapods-deintegrate'
cp_gem 'cocoapods-downloader',  'cocoapods-downloader'
cp_gem 'cocoapods-plugins',     'cocoapods-plugins'
cp_gem 'cocoapods-search',      'cocoapods-search'
cp_gem 'cocoapods-stats',       'cocoapods-stats'
cp_gem 'cocoapods-trunk',       'cocoapods-trunk'
cp_gem 'cocoapods-try',         'cocoapods-try'
cp_gem 'molinillo',             'Molinillo'
cp_gem 'nanaimo',               'Nanaimo'
cp_gem 'xcodeproj',             'Xcodeproj'